server:
  port: 8003
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiPingNB/worldconfig-repo.git     # 配置git仓库的地址
          search-paths: worldconfig-repo                        #git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 1309795179@qq.com                      # git仓库的账号
          password: liping6666                            # git仓库的密码

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8008/eureka/   # 注册中心eurka地址